services:
  db:
    container_name: db
    image: postgres:15-alpine
    restart: always
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abcd1234
      POSTGRES_DB: postgres
